# Generated by Django 5.1.6 on 2025-04-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AddField(
            model_name='patient',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
